par(mfrow=c(2,2),cex = 0.5)
plot(x=mydata2$Time, y=mydata2$Global_active_power, type = "l" ,ylab = "Global Active Power" , xlab ="")
plot(mydata2$Time,mydata2$Voltage,xlab='datetime',ylab='Voltage',type='l')
color=col=c('black','red','blue')
with(mydata2, plot(Time, as.numeric(mydata2$Sub_metering_1),  type = "l", ylab = "Energy sub metering" , xlab ="",col=color[1]), axis(2,at= c(10,20,30,40)))
with(mydata2, points(Time, as.numeric(mydata2$Sub_metering_2), type="l", col=color[2]))
with(mydata2, points(Time, as.numeric(mydata2$Sub_metering_3), type="l", col=color[3]))
legend('topright',legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=color,pch = NA, lwd = 1)
plot(mydata2$Time,mydata2$Global_reactive_power,xlab='datetime',ylab='Global_reactive_power',type='l',ylim=c(0.0,0.5))
dev.copy(png, file="C:/Users/leoolivo/Documents/plot4.png", width = 480, height = 480, units = "px")
dev.off()